linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - dupl
    - lll
    - unparam
    - nakedret
    - prealloc
    - gosec
    - revive

  disable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - wsl

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - .github
    - scripts

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linters from partially hard-vendored code
    - path: vendor/
      linters:
        - gosec
        - stylecheck
        - revive

    # Exclude false-positive security warnings
    - linters:
        - gosec
      text: "G304:" # Potential file inclusion - we control all paths
    - linters:
        - gosec
      text: "G204:" # Subprocess with variable - we control docker args
    - linters:
        - gosec
      text: "G306:" # File permissions - 0644 is appropriate for temp files

    # Exclude fieldalignment - minor optimization not worth refactoring
    - linters:
        - govet
      text: "fieldalignment:"

    # Exclude line length for data files
    - path: indexes\.go
      linters:
        - lll

    # Exclude cyclomatic complexity for functions with legitimate high complexity
    - linters:
        - gocyclo
      text: "cyclomatic complexity .* of func `detectSensor`" # Camera detection lookup
    - linters:
        - gocyclo
      text: "cyclomatic complexity .* of func `ParseWCSFile`" # FITS header parser
    - linters:
        - gocyclo
      text: "cyclomatic complexity .* of func `\\(\\*Client\\)\\.Solve`" # Main solve function
