version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - goconst
    - misspell
    - nakedret
    - prealloc
  disable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - revive
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G204
        - G304
        - G306
    govet:
      disable:
        - shadow
      enable-all: true
    lll:
      line-length: 120
      tab-width: 4
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - lll
        path: _test\.go
      - linters:
          - revive
        path: examples/
      - linters:
          - gosec
          - revive
          - staticcheck
        path: vendor/
      - linters:
          - gosec
        text: 'G304:'
      - linters:
          - gosec
        text: 'G204:'
      - linters:
          - gosec
        text: 'G306:'
      - linters:
          - govet
        text: 'fieldalignment:'
      - linters:
          - lll
        path: indexes\.go
      - linters:
          - gocyclo
        text: cyclomatic complexity .* of func `detectSensor`
      - linters:
          - gocyclo
        text: cyclomatic complexity .* of func `ParseWCSFile`
      - linters:
          - gocyclo
        text: cyclomatic complexity .* of func `\(\*Client\)\.Solve`
    paths:
      - vendor
      - .github
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
