linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - dupl
    - lll
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - gosec
    - revive

  disable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - wsl

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .github
    - scripts

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linters from partially hard-vendored code
    - path: vendor/
      linters:
        - gosec
        - stylecheck
        - revive

    # Exclude false-positive security warnings
    - linters:
        - gosec
      text: "G304:" # Potential file inclusion - we control all paths
    - linters:
        - gosec
      text: "G204:" # Subprocess with variable - we control docker args
    - linters:
        - gosec
      text: "G306:" # File permissions - 0644 is appropriate for temp files

    # Exclude fieldalignment - minor optimization not worth refactoring
    - linters:
        - govet
      text: "fieldalignment:"

    # Exclude line length for data files
    - path: indexes\.go
      linters:
        - lll

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
